[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 1000
fail_on_revert = false
seed="0x123"


[invariant]
runs = 256
depth = 32
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
